# Generated by Django 5.2.7 on 2025-11-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='upi_id',
            new_name='upi',
        ),
    ]
