# Generated by Django 5.2.7 on 2025-11-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='upi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
